services:
  tender_bot_frontend:
    build:
      context: .
      args:
        - API_URL=http://tender_bot_backend:8000
    image: tender_bot_frontend
    container_name: tender_bot_frontend
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - API_URL=http://tender_bot_backend:8000
    networks:
      - tender_bot_network

networks:
  tender_bot_network:
    external: true
